# gcloud container builds submit --config=cloudbuild.yaml .
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - beta
  - kms
  - decrypt
  - --ciphertext-file=secrets.txt.enc
  - --plaintext-file=secrets.txt
  - --location=global
  - --keyring=test-keyring
  - --key=test-key
- name: 'alpine'
  args:
  - cat
  - secrets.txt
